### ISSUE TITLE
Error trying to parse an html file

### ISSUE THREAD

**Issue by ghost** [m57/myCVT#1]
Hi, just tried to parse an outputted html file and keep running into an error.

←[1;33m[-]←[0m Parsing the HTML...
Traceback (most recent call last):
  File "C:\Users\aweldon\Downloads\myCVT-master\myCVT-master\myCVT.py", line 334
, in <module>
    soup=BeautifulSoup(open(f), "lxml")
  File "build\bdist.win32\egg\bs4__init__.py", line 156, in **init**
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requeste
d: lxml. Do you need to install a parser library?

Running win7 python 2.7 beautifulsoup4 and terminaltables

**Comment by jeszicawii** [comment]
Hey! Do you have python lxml installed?

pip install lxml

**Comment by ghost** [comment]
Did not. Just a clean install of python 2.7.11 to test this out. Works great after.

**Comment by jeszicawii** [comment]
Awesome!

**Comment by m57** [comment]
Yeah i forgot to add this one to the dependencies thanks Jess. Hope it works fine for you now :)
